Adding: Flipkart Scrapper Agent
data-artisans-centre/plugflow-core pull request #11
Opened 2024-11-28 10:29 UTC by Nilanjana1606

2024-11-29 05:18 UTC, Nilanjana1606 commented
Require a discussion regarding the merge conflicts that are automatically occuring after merging someone's agent.

2024-12-03 07:12 UTC, kanishksaleria commented on .gitignore
have you resolved the conflicts in gitignore?

2024-12-03 07:19 UTC, kanishksaleria requested changes
Few minor changes are required

2024-12-03 07:35 UTC, Nilanjana1606 commented
yes yes

2025-04-11 11:34 UTC, merged